config/routes.rb
Rails.application.routes.draw do

  # Set Posts#index as ROOT/Home page
  root to: 'posts#index'
  # Render ALL posts
  get '/posts', to: 'posts#index', as: :posts
  # Render a form to add a new post
  get '/posts/new', to: 'posts#new', as: :new_post
  # Render a single post
  get '/posts/:id', to: 'posts#show', as: :post
  # Create a post
  post '/posts', to: 'posts#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    
    # Initialize empty post object
      @post = Post.new
    #Assign attributes from form submit
      @post.title = params[:post][:title]
      @post.body = params[:post][:body]
      @post.feeling = params[:post][:feeling]
    #Save post and redirect to show page
      @post.save
      redirect_to post_path(@post)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= render '/partials/navbar' %>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav>
    <%= link_to "View All Posts", posts_path %> | <%= link_to "Add New Post", new_post_path %>
</nav>

app/views/posts/create.html.erb
<h1>Create a New Post </h1>

app/views/posts/index.html.erb
<h1>List of Blog Entries</h1>
<p>Find me in app/views/posts/index.html.erb</p>

<%= link_to "Add Post", new_post_path %>

<h2>Posts:</h3>
<ul>
    <% @posts.each do |p| %>
        <div class="post container">
            
            <div class="container">
                <li>
                    <%= link_to p.title, post_path(p) %>
                </li>
            </div>
        </div>
    <% end %>
</ul>

app/views/posts/new.html.erb
<h1>Create a New Blog Entry </h1>

<%= form_for @post do |field| %>
    <%= field.text_field(:title, { class: "form-control", placeholder: "Title" }) %>
    <%= field.text_field(:body, { placeholder: "Body" }) %>
    <%= field.text_field(:feeling, { placeholder: "Feeling" }) %>
    <%= field.submit "Submit Entry" %>
<% end %>

<h6><a href="/"> Back to Blog Index </a> </h3>

app/views/posts/show.html.erb
<h1>Blog Entry # <%= @post.id %> </h1>

<div class="container">
    <div class="container">
        <h3> " <%= @post.title %> "</h1>

        <div class="container">
            <ul>
                <li>Body: <%= @post.body %> </li>
                <li>Feeling: <%= @post.feeling %> </li>
            </ul>
        </div>
        <h6><a href="/"> Back to Blog Index </a> </h3>

 
</div>